import assert from "node:assert/strict";
import test from "node:test";
import express from "express";
import cookieParser from "cookie-parser";
import { ALL_PERMISSIONS, canCreateAccount, canEditAccount, effectivePermissions, hasAccess, requiredAccess } from "../shared/access.js";

process.env.NODE_ENV = "test";
process.env.DATABASE_URL = "";
process.env.ALLOW_IN_MEMORY_DEMO = "true";
process.env.ADMIN_EMAIL = "access-root@example.test";
process.env.ADMIN_BOOTSTRAP_PASSWORD = "access-test-root-password";
process.env.SESSION_SECRET = "account-access-test-session-secret";
const store = await import("./store.js");
const { createAccountRouter, staffGuard } = await import("./account-routes.js");
const password = "account-testing-password";

test("permission policies fail closed and customer roles never inherit staff access", () => {
  assert.deepEqual(effectivePermissions({ role: "USER", permissions: ALL_PERMISSIONS }), []);
  assert.deepEqual(effectivePermissions({ role: "INVALID", permissions: ALL_PERMISSIONS }), []);
  assert.equal(hasAccess({ role: "SUPER_ADMIN" }, "payments"), true);
  const admin = { id: "a", role: "ADMIN", permissions: ["rides"] };
  assert.equal(canCreateAccount(admin, "SUPER_ADMIN", []), false);
  assert.equal(canCreateAccount(admin, "ADMIN", ["payments"]), false);
  assert.equal(canCreateAccount(admin, "ADMIN", ["rides"]), true);
  assert.equal(canCreateAccount(admin, "USER", ["rides"]), false);
  assert.equal(canEditAccount(admin, { id: "b", role: "ADMIN" }), false);
  assert.equal(canEditAccount(admin, { id: "c", role: "USER" }), true);
  assert.equal(requiredAccess("GET", "/api/admin/unrecognized"), null);
  for (const key of ALL_PERMISSIONS) assert.ok(hasAccess({ role: "SUPER_ADMIN" }, key));
});

test("account APIs enforce creation, editing, customer isolation and immediate session revocation", async () => {
  const app = express();
  app.use(express.json(), cookieParser(), createAccountRouter());
  for (const path of ["/api/admin/dashboard", "/api/admin/rides", "/api/admin/content/fleet", "/api/admin/payments/example/capture", "/api/admin/unknown"]) app.get(path, staffGuard, (_req, res) => res.json({ ok: true }));
  const server = app.listen(0, "127.0.0.1");
  await new Promise<void>(resolve => server.once("listening", resolve));
  const port = (server.address() as { port: number }).port;
  const request = (path: string, cookie = "", method = "GET", body?: object) => fetch(`http://127.0.0.1:${port}${path}`, { method, headers: { Cookie: cookie, "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
  try {
    const root = await store.authenticate("access-root@example.test", "access-test-root-password");
    assert.ok(root);
    const rootCookie = `allan_session=${root.token}`;
    assert.equal((await request("/api/admin/users")).status, 401);
    const add = (body: object, cookie = rootCookie) => request("/api/admin/users", cookie, "POST", body);
    const crossSite = await fetch(`http://127.0.0.1:${port}/api/admin/users`, { method: "POST", headers: { Cookie: rootCookie, "Content-Type": "application/json", Origin: "https://attacker.example.test" }, body: JSON.stringify({ name: "Cross site", email: "cross-site@example.test", password, role: "USER" }) });
    assert.equal(crossSite.status, 403);
    let result = await add({ name: "Limited Admin", email: "limited@example.test", password, role: "ADMIN", permissions: ["rides"] });
    assert.equal(result.status, 201);
    const limited = (await result.json()).user;
    assert.equal("passwordHash" in limited, false);
    const staffSession = await store.authenticate(limited.email, password);
    assert.ok(staffSession);
    const limitedCookie = `allan_session=${staffSession.token}`;
    assert.equal((await request("/api/admin/rides", limitedCookie)).status, 200);
    assert.equal((await request("/api/admin/dashboard", limitedCookie)).status, 403);
    assert.equal((await request("/api/admin/content/fleet", limitedCookie)).status, 403);
    assert.equal((await request("/api/admin/payments/example/capture", limitedCookie)).status, 403);
    assert.equal((await request("/api/admin/unknown", rootCookie)).status, 403);
    assert.equal((await add({ name: "Illegal Super", email: "bad-super@example.test", password, role: "SUPER_ADMIN", permissions: [] }, limitedCookie)).status, 403);
    assert.equal((await add({ name: "Illegal Access", email: "bad-access@example.test", password, role: "ADMIN", permissions: ["payments"] }, limitedCookie)).status, 403);
    assert.equal((await add({ name: "Delegated Admin", email: "delegated@example.test", password, role: "ADMIN", permissions: ["rides"] }, limitedCookie)).status, 201);
    result = await add({ name: "Customer One", email: "CUSTOMER@example.test", password, role: "USER", permissions: [] }, limitedCookie);
    assert.equal(result.status, 201);
    const customer = (await result.json()).user;
    assert.deepEqual(customer.permissions, []);
    assert.equal(customer.email, "customer@example.test");
    assert.equal((await add({ name: "Duplicate Customer", email: customer.email, password, role: "USER" })).status, 409);
    assert.equal((await add({ name: "Customer With Access", email: "bad-customer@example.test", password, role: "USER", permissions: ["rides"] })).status, 403);
    assert.equal((await add({ name: "Unknown Access", email: "bad-key@example.test", password, role: "ADMIN", permissions: ["invented"] })).status, 400);
    assert.equal(await store.authenticate(customer.email, password), null);
    assert.equal((await request("/api/customer/login", "", "POST", { email: limited.email, password })).status, 401);
    result = await request("/api/customer/login", "", "POST", { email: customer.email, password });
    assert.equal(result.status, 200);
    const customerCookie = result.headers.get("set-cookie")!.split(";")[0];
    assert.match(customerCookie, /^allan_customer_session=/);
    const customerToken = customerCookie.split("=")[1];
    assert.equal((await request("/api/admin/users", `allan_session=${customerToken}`)).status, 403);
    assert.equal((await request("/api/customer/session", customerCookie)).status, 200);
    assert.equal((await request("/api/customer/session", `allan_customer_session=${root.token}`)).status, 401);
    assert.equal((await request(`/api/admin/users/${customer.id}`, limitedCookie, "PATCH", { role: "ADMIN", permissions: ["rides"] })).status, 403);
    assert.equal((await request(`/api/admin/users/${limited.id}`, limitedCookie, "PATCH", { permissions: ["payments"] })).status, 403);
    assert.equal((await request(`/api/admin/users/${root.user.id}`, rootCookie, "PATCH", { active: false })).status, 409);
    assert.equal(await store.updateAdmin(root.user.id, { active: false }), "LAST_SUPER_ADMIN");
    assert.equal(await store.updateAdmin(root.user.id, { role: "ADMIN", permissions: ["rides"] }), "LAST_SUPER_ADMIN");
    assert.equal((await request(`/api/admin/users/${customer.id}`, limitedCookie, "PATCH", { name: "Updated Customer" })).status, 200);
    const input = { fullName: "Customer Booking", email: customer.email, phone: "+13125550101", serviceType: "Executive Travel", pickupAt: new Date(Date.now() + 86400000).toISOString(), pickup: "Own pickup", destination: "Own destination", passengers: 1, customerUserId: customer.id };
    const owned = await store.addInquiry(input);
    await store.addInquiry({ ...input, pickup: "Other pickup", customerUserId: null });
    const other = await store.createAdmin({ email: "other@example.test", name: "Other Customer", password, role: "USER" });
    await store.addInquiry({ ...input, customerUserId: other.id, pickup: "Other customer pickup" });
    await store.addInquiry({ ...input, paymentStatus: "authorization_pending" });
    result = await request("/api/customer/bookings?customerUserId=" + other.id, customerCookie);
    const bookings = (await result.json()).bookings;
    assert.equal(bookings.length, 1);
    assert.equal(bookings[0].id, owned.inquiry.id);
    for (const key of ["email", "phone", "history", "stripePaymentIntentId", "trackingTokenHash", "customerUserId"]) assert.equal(key in bookings[0], false);
    assert.equal((await request("/api/customer/password", customerCookie, "POST", { currentPassword: "wrong", password: "new-account-password" })).status, 400);
    assert.equal((await request("/api/customer/password", customerCookie, "POST", { currentPassword: password, password: "new-account-password" })).status, 200);
    assert.equal((await request("/api/customer/bookings", customerCookie)).status, 401);
    assert.equal(await store.authenticate(customer.email, password, "customer"), null);
    const updatedSession = await store.authenticate(customer.email, "new-account-password", "customer");
    assert.ok(updatedSession);
    assert.equal((await request(`/api/admin/users/${customer.id}`, limitedCookie, "PATCH", { active: false })).status, 200);
    assert.equal(await store.sessionUser(updatedSession.token), null);
    assert.equal(await store.authenticate(customer.email, "new-account-password", "customer"), null);
    assert.equal((await request(`/api/admin/users/${limited.id}`, rootCookie, "PATCH", { permissions: ["fleet"] })).status, 200);
    assert.equal(await store.sessionUser(staffSession.token), null);
    const newStaffSession = await store.authenticate(limited.email, password);
    assert.ok(newStaffSession);
    assert.deepEqual(newStaffSession.user.permissions, ["fleet"]);
  } finally {
    server.closeAllConnections();
    await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve()));
  }
});

test("only Super Admins can change staff passwords or delete accounts, with safe session revocation", async () => {
  const app = express();
  app.use(express.json(), cookieParser(), createAccountRouter());
  const server = app.listen(0, "127.0.0.1");
  await new Promise<void>(resolve => server.once("listening", resolve));
  const port = (server.address() as { port: number }).port;
  const request = (path: string, cookie = "", method = "GET", body?: object) => fetch(`http://127.0.0.1:${port}${path}`, { method, headers: { Cookie: cookie, "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
  try {
    const root = await store.authenticate("access-root@example.test", "access-test-root-password");
    assert.ok(root);
    const rootCookie = `allan_session=${root.token}`;
    const target = await store.createAdmin({ name: "Password Target", email: "password-target@example.test", password, role: "ADMIN", permissions: ["rides"] }, root.user);
    const customer = await store.authenticate("other@example.test", password, "customer");
    const limited = await store.authenticate("limited@example.test", password);
    assert.ok(limited && customer);
    const limitedCookie = `allan_session=${limited.token}`;
    const path = `/api/admin/users/${target.id}`;
    assert.equal((await request(path + "/password", "", "POST", { password: "updated-test-password" })).status, 401);
    assert.equal((await request(path + "/password", `allan_session=${customer.token}`, "POST", { password: "updated-test-password" })).status, 403);
    assert.equal((await request(path + "/password", limitedCookie, "POST", { password: "updated-test-password" })).status, 403);
    assert.equal((await request(path, limitedCookie, "DELETE")).status, 403);
    assert.equal((await request(`/api/admin/users/${customer.user.id}`, rootCookie, "DELETE")).status, 403);
    assert.equal((await request(`/api/admin/users/${customer.user.id}/password`, rootCookie, "POST", { password: "updated-test-password" })).status, 403);
    assert.equal((await request(`/api/admin/users/${root.user.id}`, rootCookie, "DELETE")).status, 409);
    assert.equal((await request(path + "/password", rootCookie, "POST", { password: "short" })).status, 400);
    assert.equal((await request("/api/admin/users/missing/password", rootCookie, "POST", { password: "updated-test-password" })).status, 404);
    const first = await store.authenticate(target.email, password);
    const second = await store.authenticate(target.email, password);
    assert.ok(first && second);
    const result = await request(path + "/password", rootCookie, "POST", { password: "updated-test-password" });
    assert.equal(result.status, 200);
    assert.equal((await result.json()).signedOut, false);
    assert.equal(await store.sessionUser(first.token), null);
    assert.equal(await store.sessionUser(second.token), null);
    assert.equal(await store.authenticate(target.email, password), null);
    const updated = await store.authenticate(target.email, "updated-test-password");
    assert.ok(updated);
    assert.equal((await request(path, rootCookie, "DELETE")).status, 204);
    assert.equal(await store.sessionUser(updated.token), null);
    assert.equal(await store.authenticate(target.email, "updated-test-password"), null);
    assert.equal((await store.listAdmins()).some(user => user.id === target.id), false);
    assert.equal((await request(path, rootCookie, "DELETE")).status, 404);
    const extraSuper = await store.createAdmin({ name: "Disposable Super", email: "disposable-super@example.test", password, role: "SUPER_ADMIN" }, root.user);
    assert.equal((await request(`/api/admin/users/${extraSuper.id}`, rootCookie, "DELETE")).status, 204);
    const self = await request(`/api/admin/users/${root.user.id}/password`, rootCookie, "POST", { password: "root-updated-test-password" });
    assert.equal(self.status, 200);
    assert.equal((await self.json()).signedOut, true);
    assert.match(self.headers.get("set-cookie")!, /allan_session=;/);
    assert.equal(await store.sessionUser(root.token), null);
    assert.equal(await store.authenticate(root.user.email, "access-test-root-password"), null);
    assert.ok(await store.authenticate(root.user.email, "root-updated-test-password"));
  } finally {
    server.closeAllConnections();
    await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve()));
  }
});
