import "dotenv/config";
import assert from "node:assert/strict";
import test from "node:test";
import crypto from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { authenticate, changeCustomerPassword, createAdmin, deleteStaffAccount, getCustomerBookings, getInquiryByBookingRequestId, getRides, sessionUser, setStaffPassword, updateAdmin } from "./store.js";
import { completeAdminPasswordReset, issueAdminPasswordReset } from "./admin-recovery.js";

test("database account permissions, ownership and password/session changes persist", { skip: process.env.RUN_DATABASE_ACCOUNT_TESTS !== "true" }, async () => {
  const database = new PrismaClient();
  const suffix = crypto.randomUUID();
  const accounts: string[] = [];
  const bookings: string[] = [];
  const password = "persistent-account-test-password";
  try {
    const root = await createAdmin({ name: "Temporary Account Test Root", email: `root-${suffix}@example.test`, password, role: "SUPER_ADMIN" });
    accounts.push(root.id);
    const staff = await createAdmin({ name: "Temporary Limited Staff", email: `staff-${suffix}@example.test`, password, role: "ADMIN", permissions: ["rides"] }, root);
    accounts.push(staff.id);
    const customer = await createAdmin({ name: "Temporary Customer", email: `customer-${suffix}@example.test`, password, role: "USER", permissions: [] }, staff);
    accounts.push(customer.id);
    const other = await createAdmin({ name: "Temporary Other Customer", email: `other-${suffix}@example.test`, password, role: "USER" }, staff);
    accounts.push(other.id);
    const storedStaff = await database.adminUser.findUniqueOrThrow({ where: { id: staff.id } });
    assert.deepEqual(storedStaff.permissions, ["rides"]);
    assert.notEqual(storedStaff.passwordHash, password);
    assert.equal(await authenticate(customer.email, password), null);
    const staffLogin = await authenticate(staff.email, password);
    assert.ok(staffLogin);
    const first = await authenticate(customer.email, password, "customer");
    const second = await authenticate(customer.email, password, "customer");
    assert.ok(first && second);
    const template = { fullName: "Temporary Booking Fixture", email: customer.email, phone: "+13125550101", serviceType: "Account test", pickupAt: new Date(Date.now() + 86400000), pickup: "Private pickup", destination: "Private destination", passengers: 1 };
    for (const customerUserId of [customer.id, other.id, null]) {
      const booking = await database.inquiry.create({ data: { ...template, customerUserId } });
      bookings.push(booking.id);
    }
    const pending = await database.inquiry.create({ data: { ...template, customerUserId: customer.id, status: "PAYMENT_PENDING" } });
    bookings.push(pending.id);
    const mine = await getCustomerBookings(customer.id);
    assert.equal(mine.length, 1);
    assert.equal(mine[0].id, bookings[0]);
    assert.equal("email" in mine[0], false);
    assert.equal("history" in mine[0], false);
    assert.equal(await changeCustomerPassword(customer.id, "incorrect-password", "persistent-new-password"), false);
    assert.equal(await changeCustomerPassword(customer.id, password, "persistent-new-password"), true);
    assert.equal(await sessionUser(first.token), null);
    assert.equal(await sessionUser(second.token), null);
    assert.equal(await authenticate(customer.email, password, "customer"), null);
    const newLogin = await authenticate(customer.email, "persistent-new-password", "customer");
    assert.ok(newLogin);
    await updateAdmin(customer.id, { active: false }, staff);
    assert.equal(await sessionUser(newLogin.token), null);
    await updateAdmin(staff.id, { permissions: ["fleet"] }, root);
    assert.equal(await sessionUser(staffLogin.token), null);
    assert.deepEqual((await authenticate(staff.email, password))?.user.permissions, ["fleet"]);
    await assert.rejects(createAdmin({ name: "Overdelegated test", email: `blocked-${suffix}@example.test`, password, role: "ADMIN", permissions: ["payments"] }, staff), /FORBIDDEN_ACCOUNT_CREATE/);
    assert.equal(await updateAdmin(root.id, { active: false }, staff), "FORBIDDEN");
    const target = await createAdmin({ name: "Historical Test Staff", email: `delete-${suffix}@example.test`, password, role: "ADMIN", permissions: ["rides"] }, root);
    accounts.push(target.id);
    const login = await authenticate(target.email, password);
    assert.ok(login);
    const reset = await issueAdminPasswordReset(target.email, database);
    assert.equal(reset.kind, "issued");
    assert.ok(reset.kind === "issued");
    assert.equal(await setStaffPassword(target.id, "new-staff-test-password", staff), "FORBIDDEN");
    assert.equal(await deleteStaffAccount(target.id, staff), "FORBIDDEN");
    assert.equal(await setStaffPassword(target.id, "new-staff-test-password", root), "UPDATED");
    assert.equal(await sessionUser(login.token), null);
    assert.equal(await database.adminPasswordReset.count({ where: { userId: target.id } }), 0);
    assert.equal(await completeAdminPasswordReset(reset.token, "stale-reset-password", database), false);
    assert.equal(await authenticate(target.email, password), null);
    const newStaffLogin = await authenticate(target.email, "new-staff-test-password");
    assert.ok(newStaffLogin);
    const historyBooking = await database.inquiry.create({ data: { ...template, bookingRequestId: `staff-history-${suffix}` } });
    bookings.push(historyBooking.id);
    await database.inquiryNote.create({ data: { inquiryId: historyBooking.id, authorId: target.id, body: "Preserved operational note" } });
    const ride = await database.ride.create({ data: { inquiryId: historyBooking.id } });
    const message = await database.dispatchMessage.create({ data: { rideId: ride.id, adminId: target.id, reconciledById: target.id, toPhone: "+13125550101", body: "Preserved dispatch record", status: "FAILED" } });
    const deleteReset = await issueAdminPasswordReset(target.email, database, new Date(Date.now() + 60000));
    assert.equal(await deleteStaffAccount(target.id, root), "DELETED");
    assert.equal(await database.adminUser.findUnique({ where: { id: target.id } }), null);
    assert.equal(await sessionUser(newStaffLogin.token), null);
    assert.equal(await database.adminPasswordReset.count({ where: { userId: target.id } }), 0);
    assert.ok(deleteReset.kind === "issued");
    assert.equal(await completeAdminPasswordReset(deleteReset.token, "deleted-reset-password", database), false);
    const note = await database.inquiryNote.findFirstOrThrow({ where: { inquiryId: historyBooking.id } });
    assert.equal(note.body, "Preserved operational note");
    assert.equal(note.authorId, null);
    assert.equal(note.authorName, target.name);
    const dispatch = await database.dispatchMessage.findUniqueOrThrow({ where: { id: message.id } });
    assert.equal(dispatch.adminId, null);
    assert.equal(dispatch.reconciledById, null);
    assert.equal(dispatch.adminName, target.name);
    assert.equal(dispatch.reconciledByName, target.name);
    const mapped = await getInquiryByBookingRequestId(`staff-history-${suffix}`);
    assert.equal(mapped?.history[0]?.author, target.name);
    const mappedRide = (await getRides()).find(item => item.id === ride.id);
    assert.equal(mappedRide?.dispatchMessages[0]?.adminName, target.name);
    assert.equal(await deleteStaffAccount(root.id, root), "SELF_DELETE");
  } finally {
    await database.inquiry.deleteMany({ where: { id: { in: bookings } } });
    await database.adminUser.deleteMany({ where: { id: { in: accounts } } });
    await database.$disconnect();
  }
});
